// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductTest.Data;

namespace ProductTest.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200225031433_initialCreate")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("ProductTest.Models.BooleanTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BooleanTests");
                });

            modelBuilder.Entity("ProductTest.Models.PatternTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("AllSeason")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("AllTerrain")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrandTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("ColourSmoke")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Eco")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Features")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("HeavyAllTerrain")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HigherMileage")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HighwayTerrain")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Images")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("LowerNoise")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("MudTerrain")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Overview")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Performance")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("QualityCategory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SalesHookLine")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Segment")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("SemiSlick")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Synonyms")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Touring")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("TreadType")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("UltraHighPerformance")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Patterns");
                });

            modelBuilder.Entity("ProductTest.Models.SkuTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AspectRatio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrandTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Commercial")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Homologation1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Homologation2")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("LightTruck")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LoadRating1")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LoadRating2")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("MOE")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("NoiseCancelling")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PatternTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RimSize")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("RunFlat")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("SUV")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Seal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Speed")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Skus");
                });

            modelBuilder.Entity("ProductTest.Models.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Tests");
                });
#pragma warning restore 612, 618
        }
    }
}
