// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductTest.Data;

namespace ProductTest.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200221152330_SkuAndPatternInitialCreate")]
    partial class SkuAndPatternInitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("ProductTest.Models.PatternTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllSeason")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllTerrain")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrandTitle")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ColourSmoke")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Eco")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Features")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HeavyAllTerrain")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HigherMilage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HighwayTerrain")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Images")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LowerNoise")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MudTerrain")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Overview")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Performance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QualityCategory")
                        .HasColumnType("TEXT");

                    b.Property<string>("SalesHook")
                        .HasColumnType("TEXT");

                    b.Property<string>("Segment")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SemiSlick")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Synonyms")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Touring")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TreadType")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UltraHighPerformance")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Patterns");
                });

            modelBuilder.Entity("ProductTest.Models.SkuTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AspectRatio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrandTitle")
                        .HasColumnType("TEXT");

                    b.Property<int>("Commercial")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Homologation1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Homologation2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LightTruck")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoadRating1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoadRating2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MOE")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NoiseCancelling")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PatternTitle")
                        .HasColumnType("TEXT");

                    b.Property<int>("RimSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RunFlat")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SUV")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Seal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sku")
                        .HasColumnType("TEXT");

                    b.Property<char>("Speed")
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Skus");
                });
#pragma warning restore 612, 618
        }
    }
}
