// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductTest.Data;

namespace ProductTest.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200217024149_InitalCreate")]
    partial class InitalCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("ProductTest.Models.SkuTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Active")
                        .HasColumnType("TEXT");

                    b.Property<string>("AspectRatio")
                        .HasColumnType("TEXT");

                    b.Property<string>("BrandTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Commercial")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Homologation1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Homologation2")
                        .HasColumnType("TEXT");

                    b.Property<string>("LightTruck")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoadRating1")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoadRating2")
                        .HasColumnType("TEXT");

                    b.Property<string>("MOE")
                        .HasColumnType("TEXT");

                    b.Property<string>("NoiseCancelling")
                        .HasColumnType("TEXT");

                    b.Property<string>("PatternTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("RimSize")
                        .HasColumnType("TEXT");

                    b.Property<string>("RunFlat")
                        .HasColumnType("TEXT");

                    b.Property<string>("SUV")
                        .HasColumnType("TEXT");

                    b.Property<string>("Seal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sku")
                        .HasColumnType("TEXT");

                    b.Property<string>("Speed")
                        .HasColumnType("TEXT");

                    b.Property<string>("Width")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Skus");
                });
#pragma warning restore 612, 618
        }
    }
}
