// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductTest.Data;

namespace ProductTest.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200221153910_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("ProductTest.Models.PatternTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Active")
                        .HasColumnType("TEXT");

                    b.Property<string>("AllSeason")
                        .HasColumnType("TEXT");

                    b.Property<string>("AllTerrain")
                        .HasColumnType("TEXT");

                    b.Property<string>("BrandTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("ColourSmoke")
                        .HasColumnType("TEXT");

                    b.Property<string>("Eco")
                        .HasColumnType("TEXT");

                    b.Property<string>("Features")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeavyAllTerrain")
                        .HasColumnType("TEXT");

                    b.Property<string>("HigherMilage")
                        .HasColumnType("TEXT");

                    b.Property<string>("HighwayTerrain")
                        .HasColumnType("TEXT");

                    b.Property<string>("Images")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("LowerNoise")
                        .HasColumnType("TEXT");

                    b.Property<string>("MudTerrain")
                        .HasColumnType("TEXT");

                    b.Property<string>("Overview")
                        .HasColumnType("TEXT");

                    b.Property<string>("Performance")
                        .HasColumnType("TEXT");

                    b.Property<string>("QualityCategory")
                        .HasColumnType("TEXT");

                    b.Property<string>("SalesHook")
                        .HasColumnType("TEXT");

                    b.Property<string>("Segment")
                        .HasColumnType("TEXT");

                    b.Property<string>("SemiSlick")
                        .HasColumnType("TEXT");

                    b.Property<string>("Synonyms")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Touring")
                        .HasColumnType("TEXT");

                    b.Property<string>("TreadType")
                        .HasColumnType("TEXT");

                    b.Property<string>("UltraHighPerformance")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Patterns");
                });

            modelBuilder.Entity("ProductTest.Models.SkuTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Active")
                        .HasColumnType("TEXT");

                    b.Property<string>("AspectRatio")
                        .HasColumnType("TEXT");

                    b.Property<string>("BrandTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Commercial")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Homologation1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Homologation2")
                        .HasColumnType("TEXT");

                    b.Property<string>("LightTruck")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoadRating1")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoadRating2")
                        .HasColumnType("TEXT");

                    b.Property<string>("MOE")
                        .HasColumnType("TEXT");

                    b.Property<string>("NoiseCancelling")
                        .HasColumnType("TEXT");

                    b.Property<string>("PatternTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("RimSize")
                        .HasColumnType("TEXT");

                    b.Property<string>("RunFlat")
                        .HasColumnType("TEXT");

                    b.Property<string>("SUV")
                        .HasColumnType("TEXT");

                    b.Property<string>("Seal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sku")
                        .HasColumnType("TEXT");

                    b.Property<char>("Speed")
                        .HasColumnType("TEXT");

                    b.Property<string>("Width")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Skus");
                });
#pragma warning restore 612, 618
        }
    }
}
